### ISSUE TITLE
error converting nested scss rules.

### ISSUE THREAD

**Issue by samccone** [mojotech/sass2stylus#49]
SCSS

``` scss
background: {
   size: "cover";
   position: center;
}
```

---

STYL

``` stylus
background-size: cover;
background-position: center;
```
