### ISSUE TITLE
Wrap divisions in parens

### ISSUE THREAD

**Issue by kizu** [mojotech/sass2stylus#76]
If there is an expression with a division, Stylus treats it literally. So, Sass code like this:

``` Sass
$foo: 10px
.bar
  margin: $foo/2
```

would be converted to 

``` Stylus
$foo = 10px
.bar
  margin: $foo / 2
```

and would be converted by Stylus to

``` CSS
.bar {
  margin: 10px/2;
}
```

To fix it, we should wrap such expressions in parens:

``` Stylus
$foo = 10px
.bar
  margin: ($foo / 2)
```

would properly compile to

``` CSS
.bar {
  margin: 5px;
}
```
