### ISSUE TITLE
Proper lists in `for`

### ISSUE THREAD

**Issue by kizu** [mojotech/sass2stylus#78]
This example from Sass docs is not converted properly:

``` Scss
@each $animal in puma, sea-slug, egret, salamander {
  .#{$animal}-icon {
    width: 10px;
  }
}
```

right now gives

```
for $animal in puma, sea-slug, egret, salamander
  .{$animal}-icon
    width: 10px
```

which returns an error as Stylus do not understand the comma list inside `for`, so we need to convert it to a proper Stylus list, like this one:

```
for $animal in (puma sea-slug egret salamander)
  .{$animal}-icon
    width: 10px
```
