### ISSUE TITLE
Convert the simple cases of at-root

### ISSUE THREAD

**Issue by kizu** [mojotech/sass2stylus#80]
Yes, not all of the `@at-root` cases could be converted to Stylus now, but the most often used ones are easily convertable as Stylus have root reference. So, 

``` Scss
.foo {
  width: 10px;
  @at-root {
    .bar {
      height: 10px;
    }
  }
  @at-root .baz {
    padding: 10px;
  }
}
```

could be converted to

```
.foo
  width: 10px
  /
    .bar
      height: 10px
  / .baz
    padding: 10px
```

When there is a `without` or `with` yes, it couldn't be easily transformed to Stylus, but I saw the simple at-root used more often than the one with queries, so it would make sense to support at least it.
